// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    // ignore: missing_enum_constant_in_switch
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
    }

    throw UnsupportedError(
      'DefaultFirebaseOptions are not supported for this platform.',
    );
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlfggUQz1z2I8Nr_iq2PJoMloR3hK5dys',
    appId: '1:346211298375:android:a7d24ce5b5704a482d5562',
    messagingSenderId: '346211298375',
    projectId: 'gangapp-nebulova',
    storageBucket: 'gangapp-nebulova.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlfzFVwaKFZxQ6vWvnl2PgLt5bWlDjVIA',
    appId: '1:346211298375:ios:44ae98f38c0b4d792d5562',
    messagingSenderId: '346211298375',
    projectId: 'gangapp-nebulova',
    storageBucket: 'gangapp-nebulova.appspot.com',
    iosClientId: '346211298375-i164f6jjd4fe7ksb2qloi6iip2tltnsm.apps.googleusercontent.com',
    iosBundleId: 'com.example.gangappFlutter',
  );
}
